/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vuthihoaithu;

/**
 *
 * @author Vũ Thị Hoài Thu
 */
public class BT04_2 extends javax.swing.JFrame {

    /**
     * Creates new form BT05
     */
    public BT04_2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtPhanThuc1 = new javax.swing.JTextField();
        txtPhanThuc2 = new javax.swing.JTextField();
        txtPhanThuckq = new javax.swing.JTextField();
        txtPhanAo2 = new javax.swing.JTextField();
        txtPhanAo1 = new javax.swing.JTextField();
        txtPhanAokp = new javax.swing.JTextField();
        rdCong = new javax.swing.JRadioButton();
        rdTru = new javax.swing.JRadioButton();
        rdNhan = new javax.swing.JRadioButton();
        rdChia = new javax.swing.JRadioButton();
        btThucHien = new javax.swing.JButton();
        btXoa = new javax.swing.JButton();
        btTiepTuc = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Số phức");

        jLabel1.setText("Số phức 1");

        jLabel2.setText("Số phức 2");

        jLabel3.setText("Kết quả");

        jLabel5.setText("Phần thực");

        txtPhanAokp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPhanAokpActionPerformed(evt);
            }
        });

        buttonGroup1.add(rdCong);
        rdCong.setText("Cộng");

        buttonGroup1.add(rdTru);
        rdTru.setText("Trừ");

        buttonGroup1.add(rdNhan);
        rdNhan.setText("Nhân");

        buttonGroup1.add(rdChia);
        rdChia.setText("Chia");

        btThucHien.setText("Thực hiện");
        btThucHien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btThucHienMouseClicked(evt);
            }
        });

        btXoa.setText("Thoát");
        btXoa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btXoaMouseClicked(evt);
            }
        });

        btTiepTuc.setText("Tiếp tục");
        btTiepTuc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btTiepTucMouseClicked(evt);
            }
        });

        jLabel6.setText("Phần ảo");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4)
                        .addGap(97, 97, 97)
                        .addComponent(jLabel6))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addGap(36, 36, 36)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtPhanThuc2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtPhanThuc1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtPhanThuckq, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(84, 84, 84)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtPhanAo1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtPhanAo2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtPhanAokp, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(rdCong)
                                    .addGap(18, 18, 18)
                                    .addComponent(rdTru)
                                    .addGap(43, 43, 43)
                                    .addComponent(rdNhan)
                                    .addGap(34, 34, 34)
                                    .addComponent(rdChia))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(btThucHien)
                                    .addGap(52, 52, 52)
                                    .addComponent(btTiepTuc)
                                    .addGap(34, 34, 34)
                                    .addComponent(btXoa))))))
                .addContainerGap(61, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtPhanThuc1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPhanAo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtPhanThuc2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPhanAo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtPhanThuckq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPhanAokp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdCong)
                    .addComponent(rdChia)
                    .addComponent(rdNhan)
                    .addComponent(rdTru))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btThucHien)
                    .addComponent(btTiepTuc)
                    .addComponent(btXoa))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPhanAokpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPhanAokpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPhanAokpActionPerformed

    private void btThucHienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btThucHienMouseClicked
        double t1 = Double.parseDouble(txtPhanThuc1.getText());
        double a1 = Double.parseDouble(txtPhanAo1.getText());
        double t2 = Double.parseDouble(txtPhanThuc2.getText());
        double a2 = Double.parseDouble(txtPhanAo2.getText());
        if(rdCong.isSelected()){
            txtPhanThuckq.setText(Double.toString(t1 + t2));
            txtPhanAokp.setText(Double.toString(a1 + a2));
        }
        if(rdTru.isSelected()){
            txtPhanThuckq.setText(Double.toString(t1 - t2));
            txtPhanAokp.setText(Double.toString(a1 - a2));
        }
        if(rdNhan.isSelected()){
            txtPhanThuckq.setText(Double.toString(t1 * t2 - a1 * a2));
            txtPhanAokp.setText(Double.toString(t1 * a2 + a1 * t2));
        }
        if(rdChia.isSelected()){
            txtPhanThuckq.setText(Double.toString((t1 * t2 + a1 * a2) / (t2 * t2 + a2 * a2)));
            txtPhanAokp.setText(Double.toString((t2 * a1 - t1 * a2) / (t2 * t2 + a2 * a2)));
        }
    }//GEN-LAST:event_btThucHienMouseClicked

    private void btTiepTucMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btTiepTucMouseClicked
        txtPhanAo1.setText("");
        txtPhanAo2.setText("");
        txtPhanThuc1.setText("");
        txtPhanThuc2.setText("");
        txtPhanThuckq.setText("");
        txtPhanAokp.setText("");
        rdCong.setSelected(false); 
        rdTru.setSelected(false);
        rdNhan.setSelected(false);
        rdChia.setSelected(false);
    }//GEN-LAST:event_btTiepTucMouseClicked

    private void btXoaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btXoaMouseClicked
        System.exit(1);
    }//GEN-LAST:event_btXoaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BT04_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BT04_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BT04_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BT04_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BT04_2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btThucHien;
    private javax.swing.JButton btTiepTuc;
    private javax.swing.JButton btXoa;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JRadioButton rdChia;
    private javax.swing.JRadioButton rdCong;
    private javax.swing.JRadioButton rdNhan;
    private javax.swing.JRadioButton rdTru;
    private javax.swing.JTextField txtPhanAo1;
    private javax.swing.JTextField txtPhanAo2;
    private javax.swing.JTextField txtPhanAokp;
    private javax.swing.JTextField txtPhanThuc1;
    private javax.swing.JTextField txtPhanThuc2;
    private javax.swing.JTextField txtPhanThuckq;
    // End of variables declaration//GEN-END:variables
}
